version: "3.8"

services:
    # A_broker:
    #     image: eclipse-mosquitto:latest
    #     container_name: ec-broker
    #     ports:
    #         - "1883:1883"
    #         - "9001:9001"
    #     volumes:
    #         - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    #         - /mosquitto/data
    #         - /mosquitto/log
    #     restart: always
    #     tty: true
    #     networks:
    #         - local_network_1
    
    # iot_client:
    #     build:
    #         context: .
    #         dockerfile: ./Dockerfiles/client.Dockerfile
    #     command: sh -c "sleep 30"
    #     container_name: iot_client
    #     image: iot_client
    #     volumes:
    #         - ./:/app
    #     tty: true
    #     networks:
    #         - local_network_1
    
    A_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: A_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: A_
            VERBOSE_TABLE: "false"
        networks:
            local_network_1:

    B_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: B_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: B_
            VERBOSE_TABLE: "false"
        networks:
            local_network_1:
        
    C_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: C_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: C_
            VERBOSE_TABLE: "false"
        networks:
            local_network_1:

    D_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: D_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: D_
            VERBOSE_TABLE: "true"
        networks:
            local_network_1:

    E_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: E_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: E_
            VERBOSE_TABLE: "false"
        networks:
            local_network_1:

    F_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: F_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: F_
            VERBOSE_TABLE: "false"
        networks:
            local_network_1:

    G_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: G_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: G_
            VERBOSE_TABLE: "true"
        networks:
            local_network_1:

networks:
    local_network_1:
        external: false