version: "3.8"

services:

    ############################# A Services ###################################
    A_broker:
        image: eclipse-mosquitto:latest
        container_name: A_broker
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    #         - /mosquitto/data
    #         - /mosquitto/log
        restart: always
        tty: true
        networks:
            local-net-A:
                # ipv4_address: 172.16.2.2
            universal-net:
    
    A_iot_1:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        command: python3 src/iot_service.py
        container_name: A_iot_1
        image: iot_client
        volumes:
            - ./:/app
        tty: true
        environment:
            HOSTNAME: A_iot_1
            TOPIC:    temperature
        networks:
            local-net-A:

    A_iot_2:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        command: python3 src/iot_service.py
        container_name: A_iot_2
        image: iot_client
        volumes:
            - ./:/app
        tty: true
        environment:
            HOSTNAME: A_iot_2
            TOPIC:    pressure
        networks:
            local-net-A:
    
    A_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: A_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: A_
            VERBOSE_TABLE: "false"
        networks:
            local-net-A:
                # ipv4_address: 172.16.2.6
            universal-net:

    ############################# B Services ###################################
    B_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: B_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: B_
            VERBOSE_TABLE: "false"
        networks:
            local-net-B:
            universal-net:
        
    B_broker:
        image: eclipse-mosquitto:latest
        container_name: B_broker
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    #         - /mosquitto/data
    #         - /mosquitto/log
        restart: always
        tty: true
        networks:
            local-net-B:
            universal-net:

    B_iot_1:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        command: python3 src/iot_service.py
        container_name: B_iot_1
        image: iot_client
        volumes:
            - ./:/app
        tty: true
        environment:
            HOSTNAME: B_iot_1
            TOPIC:    baby_monitor
        networks:
            local-net-B:

    ########################### Other Services #################################
    C_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: C_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: C_
            VERBOSE_TABLE: "false"
        networks:
            universal-net:

    D_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: D_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: D_
            VERBOSE_TABLE: "true"
        networks:
            universal-net:

    E_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: E_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: E_
            VERBOSE_TABLE: "false"
        networks:
            universal-net:

    F_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: F_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: F_
            VERBOSE_TABLE: "false"
        networks:
            universal-net:

    G_:
        build:
            context: .
            dockerfile: ./Dockerfiles/client.Dockerfile
        container_name: G_
        image: db_node
        command: python3 src/hub.py
        tty: true
        volumes:
            - ./:/app
        environment:
            HOSTNAME: G_
            VERBOSE_TABLE: "true"
        networks:
            universal-net:

networks:
    universal-net:
      external: false
      ipam:
        driver: default
        config:
          - subnet: 172.16.1.0/24
            gateway: 172.16.1.1

    local-net-A:
        external: false
        ipam:
            driver: default
            config:
                - subnet: 172.16.2.0/24
                  gateway: 172.16.2.1

    local-net-B:
        external: false
        ipam: 
            driver: default
            config:
                - subnet: 172.16.3.0/24
                  gateway: 172.16.3.1
